site_name: Wunderbaum
# site_url: https://mar10.github.io/wunderbaum/
repo_url: https://github.com/mar10/wunderbaum

# site_description: Set the site description. This will add a meta tag to the generated HTML header.

site_author: Martin Wendt
copyright: Copyright © 2021-2024 Martin Wendt

# remote_branch: gh-pages
# remote_name: origin

theme:
  name: material
  locale: en
  include_sidebar: true
  logo: assets/tree_logo_32.png
  favicon: assets/favicon/favicon.ico

# theme:
#   name: mkdocs
#   # name: readthedocs
#   locale: en
#   include_sidebar: true

exclude_docs: |
  .*
  /templates/
  /unittest/

nav:
  - Home: "index.md"

  - "User Guide":
      - "Quick start": "tutorial/quick_start"
      - "Initialization": "tutorial/tutorial_initialize"
      - "Data Formats": "tutorial/tutorial_source"
      - Features:
          - "Render": "tutorial/tutorial_render"
          - "Styling": "tutorial/tutorial_styling"
          - "Grid": "tutorial/tutorial_grid"
          - "Edit": "tutorial/tutorial_edit"
          - "Drag'n'Drop": "tutorial/tutorial_dnd"
          - "Select": "tutorial/tutorial_select"
          - "Events": "tutorial/tutorial_events"
          - "Filter": "tutorial/tutorial_filter"
          - "Keyboard": "tutorial/tutorial_keyboard"
          - "API": "tutorial/tutorial_api"
      - "Concepts": "tutorial/concepts"
      - "Migration": "tutorial/migrate"
      - "Contribute": "tutorial/contribute"

  - "Code Reference": "https://mar10.github.io/wunderbaum/api/index.html"
  - "Online Demos": "https://mar10.github.io/wunderbaum/demo/"
  - "Changelog": "https://github.com/mar10/wunderbaum/blob/main/CHANGELOG.md"

# not_in_nav: |
#   /private.md

validation:
  omitted_files: warn
  absolute_links: warn # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn # New in MkDocs 1.6

markdown_extensions:
  - toc:
      permalink: "#"
      # baselevel: 2
      # separator: "_"
