name: mkdocs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material

      - run: mkdocs gh-deploy --force

      - name: Commit 'd' folder to 'gh-pages'
        run: |
          git fetch
          git checkout gh-pages
          git checkout main -- docs/unittest
          mv docs/unittest unittest
          ls -al
          git add unittest
          git commit -m "Add '/docs/unittest' folder from 'main' branch to /unittest"
          git push origin gh-pages

      - name: list dir
        run: |
          pwd
          ls -l
          ls -l docs
          ls -l docs/unittest
          ls -l unittest
          ls -l docs/demo
